trigger:
- '*'  # Trigger on all branches

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

steps:
- checkout: none  # Do not check out the Azure DevOps repository

- script: |
    set -x  # Enable debugging

    # Install git and python3 for URL encoding
    sudo apt-get update
    sudo apt-get install -y git python3

    # URL encode function using python
    urlencode() {
      python3 -c "import urllib.parse; print(urllib.parse.quote('''$1'''))"
    }

    # Clone the GitHub repository
    git clone --mirror https://$(urlencode ${GITHUB_TOKEN})@${GITHUB_REPO_URL} github-mirror

    # Change directory to the cloned repository
    cd github-mirror

    # Push the repository to Azure DevOps
    git push --mirror https://$(urlencode ${AZURE_PAT})@${AZURE_REPO_URL}

  displayName: 'Mirror GitHub repository to Azure DevOps'
  env:
    GITHUB_REPO_URL: $(GITHUB_REPO_URL)  # GitHub repository URL
    GITHUB_TOKEN: $(GITHUB_TOKEN)       # GitHub PAT
    AZURE_REPO_URL: $(AZURE_REPO_URL)   # Azure DevOps repository URL
    AZURE_PAT: $(AZURE_PAT)             # Azure DevOps PAT